<div class="wrap header_wrap">
   <div id="header">
       <h1><a href="index.html" class="pbg"><img src="ossweb-img/logo.png" alt="logo"></a></h1>
       <div id="nav">
         <ul class="q">
             <li><a href="index.html" title="官网首页" onclick="PTTSendClick('header','index','首页');">首页</a></li>
             <li>
                 <a href='newslist.html' onclick="PTTSendClick('header','newslist','新闻公告');">新闻公告</a>
                 <!-- <ul>
                     <li><a href="/webplat/info/news_version3/29316/33232/33545/33546/m19482/list_1.shtml"  onclick="PTTSendClick('header','header1','版本介绍');">版本介绍</a></li>
                     <li><a href="/web2017/game.shtml"   onclick="PTTSendClick('header','header2','游戏介绍');">游戏介绍</a></li>
                     <li><a href="/web2017/jobclass.shtml"   onclick="PTTSendClick('header','header3','职业介绍');">职业介绍</a></li>
                     <li><a href="javascript:alert('敬请期待');"   onclick="PTTSendClick('header','header4','游戏壁纸');">游戏壁纸</a></li>
                 </ul> -->
             </li>
             <li>
                 <a href="javascript:;">游戏资料</a>
                 <ul>
                     <li><a href="characterlist.html"  onclick="PTTSendClick('header','header2_1','武将介绍');">武将介绍</a></li>
                     <li><a href="soldierlist.html"  target="_blank"  onclick="PTTSendClick('header','header2_2','兵种介绍');">兵种介绍</a></li>
                     <!-- <li><a href="/webplat/info/news_version3/29316/33232/33238/33515/m19360/list_1.shtml"   onclick="PTTSendClick('header','header2_3','特色PK');">特色PK</a></li> -->
                 </ul>
             </li>
             <li>
                 <a href="anchor.html" onclick="PTTSendClick('header','anchor','主播专区');">主播专区</a>
                 <!-- <ul>
                     <li><a href="javascript:showDia('qqcode');"   onclick="PTTSendClick('header','header7','手Q部落');">手Q部落</a></li>
                     <li><a href="javascript:showDia('qrcode');"   onclick="PTTSendClick('header','header8','微信公众号');">微信公众号</a></li>
                     <li><a href="javascript:showDia('wxqzcode');"   onclick="PTTSendClick('header','header9','微信游戏圈');">微信游戏圈</a></li>
                     <li style="display:none"><a href="javascript:alert('敬请期待');"   onclick="PTTSendClick('header','header10','官方微博');">官方微博</a></li>
                 </ul> -->
             </li>
             <li>
                 <a href="javascript:alert('敬请期待！');" onclick="PTTSendClick('header','officialforum','官方论坛');">官方论坛</a>
                 <!-- <ul>
                     <li><a href="javascript:alert('敬请期待');"   onclick="PTTSendClick('header','header11','常见问答');">常见问答</a></li>
                     <li><a href="javascript:alert('敬请期待');"   onclick="PTTSendClick('header','header12','客服专区');">客服专区</a></li>
                     <li><a href="javascript:alert('敬请期待');"   onclick="PTTSendClick('header','header13','礼包兑换');">礼包兑换</a></li>
                 </ul> -->
             </li>
             <li>
                 <a href="javascript:alert('敬请期待！');" onclick="PTTSendClick('header','cdkey','兑换');">CDKey兑换</a>
                 <!-- <ul>
                     <li><a href="javascript:alert('敬请期待');"   onclick="PTTSendClick('header','header11','常见问答');">常见问答</a></li>
                     <li><a href="javascript:alert('敬请期待');"   onclick="PTTSendClick('header','header12','客服专区');">客服专区</a></li>
                     <li><a href="javascript:alert('敬请期待');"   onclick="PTTSendClick('header','header13','礼包兑换');">礼包兑换</a></li>
                 </ul> -->
             </li>
             <li id='tg-sns'></li>
         </ul>

       </div>
       <h2>腾讯游戏真龙</h2>
       <p class='video_box'>腾讯年度<a href="javascript:showplaypop('playpop','y0510hvu0a7',false);" class="spr video_btn" onclick="PTTSendClick('header','video','视频');">视频</a>策划巨制</p>
   </div>
</div>
