<div class="sidebar fl">
    <div class="wxcode">
        <img src="ossweb-img/qr/wx_qr.jpg" alt="">
        <p class="sp">扫一扫关注微信公众号</p>
    </div>
    <div class="qqcode">
        <img src="ossweb-img/qr/bl_qr.jpg" alt="">
        <p class="sp">扫一扫加入手Q部落</p>
    </div>
    <div class="weibo">
        <a href="//weibo.com/u/6221374881?topnav=1&wvr=6&topsug=1&is_hot=1" target="_blank" class='weibohref'>
         <span class="sp">新浪微博 <i>+</i></span>
         <img src="ossweb-img/weibo.png" alt="">
        </a>
    </div>
    <p class="kf sp">客服热线</p>
    <p class="tel">0755-83765566</p>
</div>
